sudo: required
group: deprecated-2017Q3
language: scala
services:
- docker
before_install:
- "./tools/travis/setup.sh"
install: true
script:
- "./tools/travis/build.sh"
deploy:
- provider: script
  script: "./tools/travis/publish.sh ibmfunctions $TRAVIS_TAG"
  on:
    tags: true
    all_branches: true
    repo: ibm-functions/trigger-cloudant
- provider: script
  script: "./tools/travis/publish.sh ibmfunctions latest"
  on:
    branch: master
    repo: ibm-functions/trigger-cloudant
env:
  global:
  - secure: Y4wQpLgLhNtnYQnIWiFog0XyVI2K5dhSRg47Aq+ywWJulJ9EbwQG2o8pHTd2BIADcSowl257iZuG7HKZC5gWtxlUgfTtzvX5fUnpbLBEU0862kEN6PUadh1/YIJX31kn33FdeokgcF5QzTXY6CFiIa46dP6O/msF39IdaTC/Scb1Fp8psdEZ5r4rcnj9kv5blrWPgOf63Y00MWUE5T+fEtXnbplEzF2sm5MsVxCVwCZuSsWc8gZLVLEB+QfL1hoKXMGMtfZrqTZkwZDEjYHBVLNPiNY0yNUbHCTh43SLNCJLDgGZsoHZWMIIlMVh/kdiRNjHmEEjOcGspIawpeT/N9XajbQwfcr8BZ4NO3wo5UPhCDfbZgV6B7s8mtjXrZ3ox5dGNX0FOLxUs0osSKPzYlDRwQ+vamdf4ikNh6xzffa89r4vEyVgnvP6TLcAwDuwLawzLqfGSEJcjYz1InXhHbpQX+aE3u/5djg/6JJMoSiGOGmqaRLJL5w80dAFsD2fMNW2ib8gtPoZcVwJbO2wSnjmrNYttmdO1a2hC/iF3aip28Ma3/j6DZxRICHxhcqHllzfu5Uc2wrS8aBjTfy+Dljq7NZxWoRW6Qbuy1AP0jnfkLcQ9wRha3NxAU7L9s5OYOeA4jZU/IjtkxxZ19PKxnGTkSdlSwlvv85lc6KHhhY=
  - secure: CPPfNDmjqy7Vzzoil2nb4tkCygWk9CWNvCcO29y/S3Ge9w/50ox5QKdPFbk4hxYSZ+ecKkaptc3ovBIQVIHWegrY/PN1RFUhQ7GmI7zfe8ok9xSYKQwoJdrKrAQMKJLWzsulAOzBDdmBvfXjrflKUq/iv5iGHqu4m87GvBUVhU6VfksZo6hNUfS0B7cdsahVQRPpgWe+VZGBzCEKKQZioYZeoYA1awVo3c5Mm/V4OlIbqEIYzXD0rZDAX6o7pM7hA9TEJaIIzW6SPU11Y1LhwfIBLqEm2L+SRXI2LgdkpEtMXzHm5PWb/ZbTZeSjszcWnbtRPcnET7Y2qpJYM53IDUOVE68bZc20gG7VyrlVw1UKY6VcGWQ/ZWKQtoGwuh8MtQdSAEyfNnwj+jFC2uQKqQR7Ppm/oEjmPlIagzRQaUmEXsF977lrJJAnOxkJhSnpkaAkYGZ4kbFH4HZRDm7bzpHE1o7hmtK44m9zRhDPO+OkxSdzo6FnjfBgJ/zRROw84VgZ3Idv9cPJBRF2IaXgEsGFLO+XucHF5dpj7o1Y62ZYUmHBFuKUL/HoppwKliTxtcg0AQd1rQehFdqyzb3m2TWnN76ig5jJFVTH0WiJ/jDs1l4vdFKjjI+agZ9tMwa5GJT1LAnazm3AqCbDHxj85pzeLBbjxjd6nypDJBBU4ZE=
